# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import collections.abc
import datetime
import decimal
import pandas
import polars
import typing
import typing_extensions
__all__ = [
    "Batch",
    "Delimiters",
    "Diagnostic",
    "Document",
    "EDI_835_PARSER_PATCH",
    "Envelope",
    "ParseError",
    "Result",
    "Segment",
    "Spec",
    "SpecError",
    "Stream",
    "Table",
    "Tables",
    "WriteFinding",
    "_external_diagnostic",
    "_write",
    "parse",
    "stream",
]

EDI_835_PARSER_PATCH: builtins.str
@typing.final
class Batch:
    r"""
    The tables and diagnostics of one closed loop instance (or of the end
    of the stream).
    """
    @property
    def tables(self) -> Tables:
        r"""
        The rows appended since the previous batch, by table.
        """
    @property
    def diagnostics(self) -> builtins.list[Diagnostic]:
        r"""
        The diagnostics emitted since the previous batch, in stream order.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Delimiters:
    r"""
    The five delimiters of an interchange.
    """
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]
    @property
    def element(self) -> bytes:
        r"""
        The element separator, one byte.
        """
    @property
    def component(self) -> bytes:
        r"""
        The component separator, one byte.
        """
    @property
    def segment(self) -> bytes:
        r"""
        The segment terminator, one byte.
        """
    @property
    def repetition(self) -> typing.Optional[bytes]:
        r"""
        The repetition separator, or `None` when the file has none.
        """
    @property
    def release(self) -> typing.Optional[bytes]:
        r"""
        The release character, or `None` when it is not in use.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, element: bytes = b"*", component: bytes = b":", segment: bytes = b"~", repetition: typing.Optional[bytes] = None, release: typing.Optional[bytes] = None) -> Delimiters: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Diagnostic:
    r"""
    One finding about the data of a file. A value, never raised.
    """
    @property
    def level(self) -> builtins.int:
        r"""
        The SNIP level of the rule: 1, 2 or 3.
        """
    @property
    def origin(self) -> builtins.str:
        r"""
        Who reported the finding: `"oxedi"` for the parser's own rules, the
        validator's name for an external finding.
        """
    @property
    def code(self) -> typing.Optional[builtins.str]:
        r"""
        The external validator's own code for the finding; `None` for the
        parser's own rules and for external findings without one.
        """
    @property
    def kind(self) -> builtins.str:
        r"""
        The name of the rule that failed, e.g. `RequiredElementMissing`.
        """
    @property
    def rule(self) -> builtins.str:
        r"""
        The rule that failed, as a sentence with its values.
        """
    @property
    def segment(self) -> typing.Optional[builtins.int]:
        r"""
        The index of the segment at fault; `None` at the end of the stream.
        """
    @property
    def element(self) -> typing.Optional[builtins.int]:
        r"""
        The 1-based element position, when the finding has one.
        """
    @property
    def component(self) -> typing.Optional[builtins.int]:
        r"""
        The 1-based component position, when the finding has one.
        """
    @property
    def path(self) -> builtins.str:
        r"""
        The open loops, outermost first, joined by `/`; empty at the root.
        """
    @property
    def datum(self) -> bytes:
        r"""
        The offending value as it appears in the file.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Document:
    r"""
    The file, indexed into segments and held byte for byte.
    """
    @property
    def delimiters(self) -> Delimiters:
        r"""
        The delimiters the file was indexed with.
        """
    def __len__(self) -> builtins.int: ...
    def write(self) -> bytes:
        r"""
        The file, byte for byte.
        """
    def __repr__(self) -> builtins.str: ...
    def __getitem__(self, index: builtins.int, /) -> Segment: ...

@typing.final
class Envelope:
    r"""
    Who sends and receives an interchange, when, its first control number
    and its delimiters. The writer derives the rest of the envelope: counts,
    later control numbers, codes and fixed widths.
    """
    @property
    def sender_id(self) -> builtins.str:
        r"""
        The sender id.
        """
    @property
    def sender_qualifier(self) -> builtins.str:
        r"""
        The sender id's qualifier.
        """
    @property
    def receiver_id(self) -> builtins.str:
        r"""
        The receiver id.
        """
    @property
    def receiver_qualifier(self) -> builtins.str:
        r"""
        The receiver id's qualifier.
        """
    @property
    def usage_indicator(self) -> builtins.str:
        r"""
        The usage indicator, e.g. `P` (production) or `T` (test).
        """
    @property
    def control_number(self) -> builtins.int:
        r"""
        The first control number.
        """
    @property
    def date(self) -> datetime.date:
        r"""
        The date.
        """
    @property
    def time(self) -> datetime.time:
        r"""
        The time.
        """
    @property
    def application_sender(self) -> typing.Optional[builtins.str]:
        r"""
        The functional group's sender code, when it is not the sender id.
        """
    @property
    def application_receiver(self) -> typing.Optional[builtins.str]:
        r"""
        The functional group's receiver code, when it is not the receiver id.
        """
    @property
    def line_break(self) -> builtins.bool:
        r"""
        Whether a line break follows each segment.
        """
    @property
    def delimiters(self) -> Delimiters:
        r"""
        The delimiters written.
        """
    def __new__(cls, *, sender_id: builtins.str, receiver_id: builtins.str, date: datetime.date, time: datetime.time, sender_qualifier: builtins.str = "ZZ", receiver_qualifier: builtins.str = "ZZ", usage_indicator: builtins.str = "P", control_number: builtins.int = 1, application_sender: typing.Optional[builtins.str] = None, application_receiver: typing.Optional[builtins.str] = None, delimiters: typing.Optional[Delimiters] = None, line_break: builtins.bool = False) -> Envelope:
        r"""
        `date` (a `datetime.date`) and `time` (a `datetime.time` without a
        time zone, whole seconds) stamp the interchange and the group: the
        interchange header holds the date without its century and the time
        without its seconds, the group header keeps both. `delimiters`
        defaults to `*`, `:`, `~` and the repetition separator `^`;
        `line_break` adds a line break after each segment.
        """
    def __repr__(self) -> builtins.str: ...

class ParseError(builtins.ValueError):
    r"""
    Input that cannot be indexed: its delimiters cannot be read or it exceeds the size limit; the message says what was found and where.
    """
    ...

@typing.final
class Result:
    r"""
    What one parse produced.
    """
    @property
    def document(self) -> Document:
        r"""
        The file, held losslessly.
        """
    @property
    def tables(self) -> Tables:
        r"""
        The projected tables, by name.
        """
    @property
    def spec(self) -> Spec:
        r"""
        The spec that projected the tables: the one given, or the built-in
        selected from the file's version.
        """
    @property
    def diagnostics(self) -> builtins.list[Diagnostic]:
        r"""
        Every diagnostic, in stream order.
        """
    @property
    def payer(self) -> builtins.dict[builtins.str, builtins.str | None] | None:
        r"""
        The payer organization from the `payer_*` columns of `payments`, or
        `None` when the file has none.
        """
    @property
    def payee(self) -> builtins.dict[builtins.str, builtins.str | None] | None:
        r"""
        The payee organization from the `payee_*` columns of `payments`, or
        `None` when the file has none.
        """
    def count_claims(self) -> builtins.int:
        r"""
        The rows of `claims`.
        """
    def count_patients(self) -> builtins.int:
        r"""
        The distinct non-null values of `claims.patient_id`. Ids are text:
        `0123` and `123` are two patients, where edi-835-parser reads both as
        the number 123 and counts one.
        """
    def sum_payments(self) -> decimal.Decimal:
        r"""
        The sum of `payments.total_payment_amount`, as a `Decimal` at the
        column's scale.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Segment:
    r"""
    One segment of a document, read from the document on access.
    """
    @property
    def index(self) -> builtins.int:
        r"""
        The 0-based position of the segment in the document.
        """
    @property
    def id(self) -> bytes:
        r"""
        The segment identifier; empty for an empty frame.
        """
    @property
    def elements(self) -> builtins.list[builtins.bytes | builtins.list[builtins.bytes]]:
        r"""
        The elements in X12 order (`elements[0]` is `XX01`): `bytes` for a
        simple element, a list of `bytes` for a composite one.
        """
    @property
    def raw(self) -> bytes:
        r"""
        The exact bytes of the segment: leading trivia, body and terminator.
        """
    @property
    def span(self) -> tuple[builtins.int, builtins.int]:
        r"""
        The segment's byte range in the input, `(start, end)` with `end`
        exclusive: leading trivia, body and terminator, as `raw` holds them.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Spec:
    r"""
    The loop structure, element definitions and tables of a file format.
    """
    @staticmethod
    def builtin(version: builtins.str = "5010") -> Spec:
        r"""
        The built-in 835 spec of `version`, `"5010"` (the default) or
        `"4010"`; raises `ValueError` for any other version.
        """
    @staticmethod
    def from_json(json: builtins.str) -> Spec:
        r"""
        The spec described by `json`; raises `SpecError` with the core message
        when it is not valid.
        """
    def patch(self, patch: builtins.str | builtins.dict[builtins.str, typing.Any]) -> Spec:
        r"""
        A new spec with `patch` (a dict or JSON text) merged over this one;
        raises `SpecError` when the result is not valid.
        """
    def to_json(self) -> builtins.str:
        r"""
        The spec as JSON text.
        """
    def loops(self) -> builtins.list[builtins.str]:
        r"""
        The loop names, in spec order.
        """
    def __repr__(self) -> builtins.str: ...

class SpecError(builtins.ValueError):
    r"""
    A spec that cannot be loaded or patched; the message names the rule, the loop and key, and the datum.
    """
    ...

@typing.final
class Stream:
    r"""
    Iterates the batches of a file. Each step runs with the GIL released.
    
    A stream must be advanced from one thread at a time: a `next()` that finds
    another thread inside a step raises a `RuntimeError` naming the stream;
    unlike a generator, it does not raise `ValueError`.
    """
    def __iter__(self) -> Stream: ...
    def __next__(self) -> Batch: ...

@typing.final
class Table:
    r"""
    One projected table. Shares the tables it belongs to.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        The table name.
        """
    @property
    def columns(self) -> builtins.list[builtins.str]:
        r"""
        The column names, in order.
        """
    def __len__(self) -> builtins.int: ...
    def to_polars(self) -> polars.DataFrame:
        r"""
        The table as a polars `DataFrame`, through the Arrow capsule.
        """
    def to_pandas(self) -> pandas.DataFrame:
        r"""
        The table as a pandas `DataFrame`, through `pyarrow`.
        """
    def render(self) -> builtins.str:
        r"""
        The table as text: title, header and one line per row.
        """
    def __arrow_c_stream__(self, requested_schema: builtins.object | None = None) -> typing_extensions.CapsuleType:
        r"""
        Exports the table as an Arrow stream of one record batch, sharing
        the column buffers. `requested_schema` is ignored, as the protocol
        allows: the table keeps its own types.
        """
    def __arrow_c_array__(self, requested_schema: builtins.object | None = None) -> builtins.tuple[typing_extensions.CapsuleType, typing_extensions.CapsuleType]:
        r"""
        Exports the table as one Arrow struct array and its schema, sharing
        the column buffers. `requested_schema` is ignored, as the protocol
        allows.
        """
    def __arrow_c_schema__(self) -> typing_extensions.CapsuleType:
        r"""
        Exports the table's schema.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Tables:
    r"""
    The tables of one parse or one batch, by name. Shared, never copied.
    """
    @property
    def spec(self) -> Spec:
        r"""
        The spec that projected the tables, which `write` uses by default.
        """
    def keys(self) -> builtins.list[builtins.str]:
        r"""
        The table names, in spec order.
        """
    def __len__(self) -> builtins.int: ...
    def __iter__(self) -> collections.abc.Iterator[builtins.str]: ...
    def render(self) -> builtins.str:
        r"""
        Every table as text: title, header and one line per row.
        """
    def to_polars(self) -> builtins.dict[builtins.str, polars.DataFrame]:
        r"""
        Every table as a polars `DataFrame`, by name, in table order.
        """
    def to_pandas(self) -> builtins.dict[builtins.str, pandas.DataFrame]:
        r"""
        Every table as a pandas `DataFrame`, by name, in table order.
        """
    def __repr__(self) -> builtins.str: ...
    def __contains__(self, name: builtins.object, /) -> builtins.bool: ...
    def __getitem__(self, name: builtins.str, /) -> Table: ...

@typing.final
class WriteFinding:
    r"""
    One reason tables do not make a valid file. A value, never raised.
    """
    @property
    def kind(self) -> builtins.str:
        r"""
        The kind of finding, e.g. `MissingParent` or `ReadBack`.
        """
    @property
    def table(self) -> typing.Optional[builtins.str]:
        r"""
        The table at fault, when a table is.
        """
    @property
    def row(self) -> typing.Optional[builtins.int]:
        r"""
        The row at fault (its position in the table), when a row is.
        """
    @property
    def column(self) -> typing.Optional[builtins.str]:
        r"""
        The column at fault, when a column is.
        """
    @property
    def field(self) -> typing.Optional[builtins.str]:
        r"""
        The envelope field at fault, when one is.
        """
    @property
    def diagnostic(self) -> typing.Optional[Diagnostic]:
        r"""
        The diagnostic of reading the written file back, for a `ReadBack`.
        """
    @property
    def message(self) -> builtins.str:
        r"""
        The finding as one sentence: the rule, where and the value.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

def _external_diagnostic(origin: builtins.str, message: builtins.str, level: builtins.int, code: typing.Optional[builtins.str] = None, segment: typing.Optional[builtins.int] = None, element: typing.Optional[builtins.int] = None, component: typing.Optional[builtins.int] = None, datum: bytes = b"") -> Diagnostic:
    r"""
    Builds a `Diagnostic` for a finding reported by an external validator; internal.
    """

def _write(tables: Tables | collections.abc.Mapping[builtins.str, typing.Any], envelope: Envelope, spec: typing.Optional[Spec] = None, allow_findings: builtins.bool = False) -> tuple[bytes, builtins.list[WriteFinding]]:
    r"""
    Writes tables as one interchange; internal, see `oxedi.write`. Returns
    the bytes and the findings, which are empty unless `allow_findings`.
    """

def parse(data: typing_extensions.Buffer, spec: typing.Optional[Spec] = None, delimiters: typing.Optional[Delimiters] = None) -> Result:
    r"""
    Parses a whole file: indexes every segment, runs the loop engine, the
    envelope checker and the projector, and returns the document, the
    tables and every diagnostic. Without `spec`, the built-in spec of the
    version the file declares is used, else the default one.
    """

def stream(data: typing_extensions.Buffer, spec: typing.Optional[Spec] = None, by: builtins.str = "transaction", delimiters: typing.Optional[Delimiters] = None) -> Stream:
    r"""
    Walks a file and yields a batch each time an instance of loop `by`
    closes, and one more at the end when anything is left. Without `spec`,
    the built-in spec of the version the file declares is used, else the
    default one.
    """

